version: "2"

# SERVICES CONTAINERS SHARED NETWORK
networks:
  basma-network:
    driver: bridge

services:
# API GATEWAY SERVICE
  apigetway:
      image: basma_api_gateway:v1
      build:
        context: ./api-gateway
        dockerfile: Dockerfile
      container_name: api_getway
      ports:
        - 3000:8080
      networks:
      - basma-network
# AUTHENTISATION SERVICE
  authservice:
    image: basma_auth_service:v1
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - 3001:8080
    networks:
      - basma-network
# FRONT SERVICE
  frontservice:
    image: basma_front_service:v1
    build:
      context: ./front-service
      dockerfile: Dockerfile
    container_name: client_service
    ports:
      - 4200:80
    networks:
      - basma-network
# ORDERS SERVICE
  ordersservice:
    image: basma_orders_service:v1
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    container_name: orders_service
    ports:
      - 3002:8080
    networks:
      - basma-network
# PRODUCTS SERVICE
  productsservice:
    image: basma_products_service:v1
    build:
      context: ./products-service
      dockerfile: Dockerfile
    container_name: products_service
    ports:
      - 3003:8080
    networks:
      - basma-network
# USERS SERVICE
  userseservice:
    image: basma_users_service:v1
    build:
      context: ./users-service
      dockerfile: Dockerfile
    container_name: users_service
    ports:
      - 3004:8080
    networks:
      - basma-network

# Services Databases
  apigetwaydatabase:
    image: mysql:8.0.28
    container_name: apigetway_database
    ports:
      - 3301:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: apigetway_database
    volumes:
      - ./backup/apigetway-database:/var/lib/mysql
  authdatabase:
    image: mysql:8.0.28
    container_name: auth_database
    ports:
      - 3302:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: auth_database
    volumes:
      - ./backup/auth-database:/var/lib/mysql
  ordersdatabase:
    image: mysql:8.0.28
    container_name: orders_database
    ports:
      - 3303:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: orders_database
    volumes:
      - ./backup/orders-database:/var/lib/mysql
  productsdatabase:
    image: mysql:8.0.28
    container_name: products_database
    ports:
      - 3304:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: products_database
    volumes:
      - ./backup/products-database:/var/lib/mysql
  usersdatabase:
    image: mysql:8.0.28
    container_name: users_database
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: users_database
    volumes:
      - ./backup/users-database:/var/lib/mysql